### ISSUE TITLE
Comprehensive TODO List

### ISSUE THREAD

**Issue by abhabongse** [abhabongse/relationalcalculus-alloy#1]
## Language Parser
- [ ] Implement transformer from Lark parsed tree into internal AST

### Translation from AST into Alloy program
- [ ] Use node transformer to convert AST into Alloy program

### Alloy Verification Interfaces
- [ ] Textual analysis for Alloy programs _(to be expanded)_
- [ ] Visualization of Alloy counter-examples _(to be expanded)_

### Additional Verification Features
- [ ] Multiple scalar types in databases
- [ ] Total ordering on scalar types with comparison operators
- [ ] Functional dependencies declaration in database schemata
- [ ] Primary keys, candidate keys, unique keys (dependent of functional dependencies)

**Comment by abhabongse** [comment]
ASDL might be fun, but it is a waste of time. Might use ANTLR instead.

**Comment by abhabongse** [comment]
Okay, ANTLR is too heavy of a metal; use [LARK](https://github.com/lark-parser/lark) instead.

**Comment by abhabongse** [comment]
Commenced on using [Lark Parser](https://github.com/lark-parser/lark).
